package/iot_ble_server: update
Signed-off-by: Mikołaj Rosowski <m.rosowski1@wp.pl>

diff --git a/package/iot_ble_server/S99iot_ble_server b/package/iot_ble_server/S99iot_ble_server
--- a/package/iot_ble_server/S99iot_ble_server
+++ b/package/iot_ble_server/S99iot_ble_server
@@ -1,38 +1,70 @@
 #!/bin/sh
 
-DAEMON=/usr/bin/iot_ble_server
-PIDFILE=/var/run/iot_ble_server.pid
+DAEMON="iot_ble_server"
+PIDFILE="/var/run/$DAEMON.pid"
 
+# shellcheck source=/dev/null
+[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"
+
+# BusyBox' syslogd does not create a pidfile, so pass "-n" in the command line
+# and use "--make-pidfile" to instruct start-stop-daemon to create one.
 start() {
-    echo "Starting BLE HTTP server"
-    start-stop-daemon -S -q -m -p $PIDFILE -x $DAEMON -- &
+    printf 'Starting %s: ' "$DAEMON"
+    # shellcheck disable=SC2086 # we need the word splitting
+    start-stop-daemon \
+        -S \
+        -q \
+        -b \
+        -m \
+        -p "$PIDFILE" \
+        -x /bin/sh -- \
+        -c "sleep 5 && /usr/bin/$DAEMON 2>&1 | logger -t $DAEMON"
+    status=$?
+    if [ "$status" -eq 0 ]; then
+        echo "OK"
+    else
+        echo "FAIL"
+    fi
+    return "$status"
 }
 
 stop() {
-    echo "Stopping BLE HTTP server"
-    start-stop-daemon -K -q -p $PIDFILE
+    printf 'Stopping %s: ' "$DAEMON"
+    start-stop-daemon \
+        -K \
+        -q \
+        -p "$PIDFILE"
+    status=$?
+    if [ "$status" -eq 0 ]; then
+        echo "OK"
+    else
+        echo "FAIL"
+        return "$status"
+    fi
+    while start-stop-daemon -K -t -q -p "$PIDFILE" \
+        --exec "/sbin/$DAEMON"; do
+        sleep 0.1
+    done
+    rm -f "$PIDFILE"
+    return "$status"
 }
 
 restart() {
     stop
-    sleep 10
+    sleep 2
     start
 }
 
 case "$1" in
-    start)
-        start
-        ;;
-    stop)
-        stop
-        ;;
-    restart)
-        restart
-        ;;
-    *)
-        echo "Usage: $0 {start|stop|restart}"
-        exit 1
-        ;;
+start | stop | restart)
+    "$1"
+    ;;
+reload)
+    # Restart, since there is no true "reload" feature.
+    restart
+    ;;
+*)
+    echo "Usage: $0 {start|stop|restart|reload}"
+    exit 1
+    ;;
 esac
-
-exit 0
